# Site settings
title: PANDORA Honeymoon Collection
client:
  name: PANDORA
  link: "https://uk.pandora.net/en/gifts/wedding-gifts/?cid=disp:customcontent:e:en-gb::LifeMoments:SecretEscapes:SS18:bn:::internal"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Secret Escapes and PANDORA have curated our top picks of honeymoons to make your newlywed life start the right way. From long, dreamy beaches under tropical sunshine to cosy mini-moons perfect for getting away from it all immediately after the wedding, explore our collection of unmissable luxury escapes in spellbinding locations.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/pandora" # the subpath of your site, e.g. /blog/
img:     "/pandora/_assets/img"
css:     "/pandora/_assets/css"
js:      "/pandora/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed