
- title: Two Hearts Hoop Earrings
  id: two-hearts-hoop-earrings
  link: >
    http://estore-uk.pandora.net/earrings/hoops/two-hearts-hoop-earrings/296576.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Silver Key Locket
  id: silver-key-locket
  link: >
    http://estore-uk.pandora.net/necklaces/necklaces-with-pendants/heart-key-locket-necklace---medium/396581CZ.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Love Lock Ring
  id: love-lock-ring
  link: >
    http://estore-uk.pandora.net/rings/individual-rings/love-lock-ring/196571.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Moments Silver Lock Your Promise Heart Clasp Bracelet
  id: moments-smooth-silver-bracelet
  link: >
    http://estore-uk.pandora.net/bracelets/chains/moments-silver-lock-your-promise-heart-clasp-bracelet/596586FPC.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Two Hearts Ring
  id: two-hearts-open-silver-ring
  link: >
    http://estore-uk.pandora.net/valentine-s/two-hearts-ring/196572CZ.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: ESSENCE PANDORA Rose Bracelet
  id: rose-essence-bracelet
  link: >
    http://estore-uk.pandora.net/bracelets/chains/essence-pandora-rose-bracelet/586000.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: I Love You Pendant Charm
  id: i-love-you-two-tone-pendant-charm
  link: >
    http://estore-uk.pandora.net/charms/pendant-charms/i-love-you-pendant-charm/786596CZR.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Shining Elegance Clip
  id: rose-shining-elegance-clip
  link: >
    http://estore-uk.pandora.net/charms/clips/shining-elegance-clip/781817CZ.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Two Hearts Ring
  id: rose-two-hearts-ring
  link: >
    http://estore-uk.pandora.net/valentine-s/two-hearts-ring/186570CZR.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Explosion of Love Charm
  id: explosion-of-love-charm
  link: >
    http://estore-uk.pandora.net/charms/charms/explosion-of-love-charm/796555CZSMX.html/?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Pink Heart Key Locket Necklace
  id: pink-floating-locket-heart-key
  link: >
    http://estore-uk.pandora.net/necklaces/necklaces-with-pendants/pink-heart-key-locket-necklace---large/396584FPC.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Kisses All Around Glass Murano Charm
  id: kisses-all-around-glass-charm
  link: >
    http://estore-uk.pandora.net/charms/charms/kisses-all-around-glass-murano-charm/796598.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Dazzling Droplets Stud Earrings
  id: gold-dazzling-droplets-stud-earrings
  link: >
    http://estore-uk.pandora.net/earrings/studs/dazzling-droplets-earrings/256212CZ.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Classic Elegance Ring
  id: rose-classic-elegance-ring
  link: >
    http://estore-uk.pandora.net/rings/individual-rings/classic-elegance-ring/180946CZ.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Puzzle Heart Ring
  id: two-tone-puzzle-heart-ring
  link: >
    http://estore-uk.pandora.net/rings/stacking-rings/puzzle-heart-ring/196548.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: July Droplet Birthstone Ring
  id: july-birthstone-ring
  link: >
    http://estore-uk.pandora.net/rings/stacking-rings/july-droplet-birthstone-ring/191012SRU.html?cid=em:ge:e:en-gb::::VAL18:ot: