
- title: Two Hearts Hoop Earrings
  id: two-hearts-hoop-earrings
  link: >
    http://estore-uk.pandora.net/earrings/hoops/two-hearts-hoop-earrings/296576.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Silver Key Locket
  id: silver-key-locket
  link: >
    http://estore-uk.pandora.net/necklaces/necklaces-with-pendants/heart-key-locket-necklace---medium/396581CZ.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Love Lock Ring
  id: love-lock-ring
  link: >
    http://estore-uk.pandora.net/rings/individual-rings/love-lock-ring/196571.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Moments Silver Lock Your Promise Heart Clasp Bracelet
  id: moments-smooth-silver-bracelet
  link: >
    http://estore-uk.pandora.net/bracelets/chains/moments-silver-lock-your-promise-heart-clasp-bracelet/596586FPC.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Two Hearts Ring
  id: two-hearts-open-silver-ring
  link: >
    http://estore-uk.pandora.net/valentine-s/two-hearts-ring/196572CZ.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: ESSENCE PANDORA Rose Bracelet
  id: rose-essence-bracelet
  link: >
    http://estore-uk.pandora.net/bracelets/chains/essence-pandora-rose-bracelet/586000.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: I Love You Pendant Charm
  id: i-love-you-two-tone-pendant-charm
  link: >
    http://estore-uk.pandora.net/charms/pendant-charms/i-love-you-pendant-charm/786596CZR.html?cid=em:ge:e:en-gb::::VAL18:ot:

- title: Shining Elegance Clip
  id: rose-shining-elegance-clip
  link: >
    http://estore-uk.pandora.net/charms/clips/shining-elegance-clip/781817CZ.html?cid=em:ge:e:en-gb::::VAL18:ot:
