
- title: Two Hearts Hoop Earrings
  id: two-hearts-hoop-earrings
  link: >
    https://uk.pandora.net/en/earrings/hoops/two-hearts-hoop-earrings/296576.html?cid=disp:customcontent:e:en-gb::LifeMoments:SecretEscapes:SS18:ot:::internal

- title: Heart Key Locket Necklace
  id: heart-key-locket-necklace
  link: >
    https://uk.pandora.net/en/necklaces/necklaces-with-pendants/heart-key-locket-necklace---medium/396581CZ.html?cid=disp:customcontent:e:en-gb::LifeMoments:SecretEscapes:SS18:ot:::internal

- title: Love Lock Ring
  id: love-lock-ring
  link: >
    https://uk.pandora.net/en/rings/statement/love-lock-ring/196571.html?cid=disp:customcontent:e:en-gb::LifeMoments:SecretEscapes:SS18:ot:::internal

- title: Moments Silver Lock Your Promise Heart Clasp Bracelet
  id: moments-smooth-silver-bracelet
  link: >
    https://uk.pandora.net/en/bracelets/chains/moments-silver-lock-your-promise-heart-clasp-bracelet/596586FPC.html?cid=disp:customcontent:e:en-gb::LifeMoments:SecretEscapes:SS18:ot:::internal

- title: Two Hearts Ring
  id: two-hearts-ring
  link: >
    https://uk.pandora.net/en/rings/statement/two-hearts-ring/196572CZ.html?cid=disp:customcontent:e:en-gb::LifeMoments:SecretEscapes:SS18:ot:::internal

- title: ESSENCE PANDORA Rose Bracelet
  id: essence-rose-bracelet
  link: >
    https://uk.pandora.net/en/bracelets/chains/essence-pandora-rose-bracelet/586000.html?cid=disp:customcontent:e:en-gb::LifeMoments:SecretEscapes:SS18:ot:::internal

- title: I Love You Forever Pendant Charm
  id: i-love-you-forever-pendant-charm
  link: >
    https://uk.pandora.net/en/gifts/anniversary-gifts/i-love-you-forever-pendant-charm/792042CZ.html?cid=disp:customcontent:e:en-gb::LifeMoments:SecretEscapes:SS18:ot:::internal

- title: Shining Elegance Clip
  id: shining-elegance-clip
  link: >
    https://uk.pandora.net/en/charms/clips/shining-elegance-clip/781817CZ.html?cid=disp:customcontent:e:en-gb::LifeMoments:SecretEscapes:SS18:ot:::internal
